Repository cmu15122/q-prime, pull requests merged in 2023-01, with the labels that each got.

#204 fixed topics csv upload
  server/controllers/settings.js
Labels: state: shipit!

#207 Change application to run on subpath
  README.md
  client/public/index.html
  client/src/App.tsx
  client/src/components/navbar/Navbar.tsx
  client/src/components/navbar/OHQueueHeader.tsx
  client/src/http-common.tsx
Labels: enhancement, size: S, state: shipit!

#211 Add preferred name handling to more places
  client/src/contexts/StudentDataContext.tsx
  server/controllers/home.js
  server/controllers/queue.js
  server/controllers/sockets.js
  server/tests/queue.test.js
  types/StudentData.ts
Labels: bug, size: S, state: shipit!

#213 Fixes TA Zoom URL settings
  client/src/components/home/student/MessageOverlay.tsx
  client/src/components/home/student/StudentMain.tsx
  client/src/components/home/student/TAHelpingOverlay.tsx
  client/src/components/home/ta/StudentEntries.tsx
  client/src/components/home/ta/TailOptions/StudentStatus.tsx
  client/src/components/settings/VideoChatSettings.tsx
  client/src/contexts/StudentDataContext.tsx
  server/controllers/home.js
  server/controllers/queue.js
  server/controllers/sockets.js
  server/tests/queue.test.js
  types/StudentData.ts
Labels: bug, size: S, state: shipit!

#217 open github issues link in new tab
  client/src/components/home/Footer.tsx
Labels: enhancement, state: shipit!

#220 Created deployment actions for production and preview environments
  .github/workflows/deploy_prod.yml
  .github/workflows/preview.yml
Labels: state: shipit!

#221 Fixed bugs with metrics page (fixes #205)
  client/src/components/metrics/CumulativeStats.tsx
  client/src/components/metrics/Graph.tsx
  client/src/components/metrics/OverallStats.tsx
  client/src/components/metrics/PersonalStats.tsx
  server/controllers/metrics.js
Labels: state: shipit!
